// generate_data.js
// Run: node generate_data.js
const fetch = require('node-fetch');
const fs    = require('fs');

// ← YOUR API KEY HERE ↓
const apiKey = 'ca3c6b07-0e0e-4774-a57d-6d0bb178801d';

// 1) Your daily schedule:
const schedule = {
  "2025-05-07": ["腰","蓋","初","夏","省","桐","包","類","資","影","敦","爾","悟","拆"],
  "2025-05-08": ["取","抬","腰","蓋","初","夏","技","票","周","例","擁","擠","盛","隨"]
};
// flatten + dedupe:
const chars = Array.from(new Set(Object.values(schedule).flat()));

async function fetchDetail(ch) {
  // ✅ Use v2/Detail with "term" parameter
  const url = `https://pedia.cloud.edu.tw/api/v2/Detail?term=${encodeURIComponent(ch)}&api_key=${apiKey}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const { data } = await res.json();
  return {
    bopomofo:    data.bopomofo     || '',
    definitions: data.definitions || [],
    examples:    data.examples    || [],
    phrases2:    data.phrases_2   || [],
    phrases3:    data.phrases_3   || [],
    phrases4:    data.collocations_4 || []
  };
}

(async () => {
  const details = {};
  for (const ch of chars) {
    try {
      const d = await fetchDetail(ch);
      details[ch] = { char: ch, ...d };
      console.log(`✅  Fetched ${ch}`);
    } catch (e) {
      console.warn(`⚠️  Failed ${ch}: ${e.message}`);
      details[ch] = { char:ch, bopomofo:'', definitions:[], examples:[], phrases2:[], phrases3:[], phrases4:[] };
    }
  }

  // 3) Write out data.js
  const out = [
    '// AUTO-GENERATED by generate_data.js',
    'export default ',
    JSON.stringify(details, null, 2),
    ';'
  ].join('\n');
  fs.writeFileSync('data.js', out, 'utf-8');
  console.log(`🎉 data.js written with ${Object.keys(details).length} entries`);
})();
